name: Build Mida Pro APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # فك ضغط الملف بالاسم الجديد الذي حددته
      - name: Unzip Mida Pro Source
        run: unzip mida-steganography-proo.zip

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # إعطاء صلاحية التنفيذ لملف البناء (ضروري جداً)
      - name: Grant Execute Permission
        run: chmod +x gradlew

      # بناء التطبيق (Debug APK)
      - name: Build Mida APK
        run: ./gradlew assembleDebug

      # رفع الملف الناتج لتحميله
      - name: Upload Mida APK
        uses: actions/upload-artifact@v4
        with:
          name: Mida-Pro-Release
          path: "**/build/outputs/apk/debug/*.apk"
          
