name: Build Mida APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # تحديث للأصدار v4

      - name: Unzip Source
        run: unzip mida-steganography.zip

      - name: set up JDK 17
        uses: actions/setup-java@v4 # تحديث للأصدار v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4 # الحل هنا: غيرنا v3 لـ v4
        with:
          name: Mida-App-Package
          path: "**/*.apk"
